package com.meelano.builder.ui

/** Minimal EN/FA strings with runtime toggle (no activity restart needed). */
object S {
    private val en = mapOf(
        "headline" to "What do you want to make today?",
        "hint" to "Type your idea...",
        "platform_android" to "🤖 Android (APK)",
        "platform_windows" to "🪟 Windows (.exe + Setup)",
        "need_idea" to "Type your idea first!",
        "need_platform" to "Pick at least one platform",
        "building" to "🔨 Building...",
        "my_apps" to "My apps",
        "templates" to "Templates",
        "settings" to "Settings",
        "builder" to "Builder",
        "about" to "About",
        "back" to "← Back",
        "preview" to "👁 Preview",
        "open_preview" to "👁 Open preview",
        "download" to "⬇ Download",
        "install" to "📲 Install",
        "share_qr" to "Share via QR",
        "downloading" to "Downloading…",
        "downloaded" to "Saved. Tap Install.",
        "install_hint" to "If Android asks, allow “Install unknown apps” for MeeLano Builder.",
        "server_url" to "Builder server URL",
        "test" to "Test",
        "connected" to "✅ Connected",
        "conn_fail" to "❌ Cannot reach server",
        "language" to "Language",
        "auto_mode" to "AUTO mode (build both platforms)",
        "ai_key" to "AI key (optional, OpenAI-compatible)",
        "ai_base" to "AI base URL (optional)",
        "ai_hint" to "Without a key, the built-in template engine is used. With a key, the AI customises the design for any idea.",
        "about_text" to "Type one short sentence — get a Windows program (.exe + Setup installer) and an Android app (.apk) with direct install. Sources + live preview are always included.",
        "refresh" to "Refresh",
        "empty_apps" to "Nothing yet — type an idea on the Builder tab 👆",
        "build_this" to "Build this →",
        "status_queued" to "queued",
        "status_building" to "building",
        "status_done" to "done",
        "status_partial" to "partial",
        "status_failed" to "failed",
        "err_create" to "Could not start build: ",
        "api_token" to "Server API token (if the server requires one)",
        "api_token_hint" to "Same value as BUILDER_TOKEN on your server. Leave empty if the server has no token.",
        "err_network" to "Cannot reach the server. Check the URL, Wi-Fi, and that start_server is running.",
        "err_unauth" to "Wrong API token — fix it in Settings.",
        "retry" to "↻ Retry",
        "srv_help_title" to "📡 How to connect your phone",
        "srv_help_body" to "1) On your PC open the server folder and double-click start_server.bat (Windows) or run ./start_server.sh\n2) Connect your phone to the SAME Wi-Fi as the PC\n3) Type the http://xxx.xxx.xxx.xxx:8000 address shown in the black window into Server URL above\n4) Tap Test ✓ — then build anything!",
    )
    private val fa = mapOf(
        "headline" to "امروز می‌خوای چی بسازی؟",
        "hint" to "ایده‌ات رو بنویس...",
        "platform_android" to "🤖 اندروید (APK)",
        "platform_windows" to "🪟 ویندوز (.exe + فایل نصب)",
        "need_idea" to "اول ایده‌ات رو بنویس!",
        "need_platform" to "حداقل یک پلتفرم انتخاب کن",
        "building" to "🔨 در حال ساخت...",
        "my_apps" to "برنامه‌های من",
        "templates" to "قالب‌ها",
        "settings" to "تنظیمات",
        "builder" to "سازنده",
        "about" to "درباره",
        "back" to "← بازگشت",
        "preview" to "👁 پیش‌نمایش",
        "open_preview" to "👁 باز کردن پیش‌نمایش",
        "download" to "⬇ دانلود",
        "install" to "📲 نصب",
        "share_qr" to "اشتراک با QR",
        "downloading" to "در حال دانلود…",
        "downloaded" to "ذخیره شد. «نصب» رو بزن.",
        "install_hint" to "اگه اندروید پرسید، گزینه «نصب برنامه‌های ناشناس» رو برای میلانو بیلدر مجاز کن.",
        "server_url" to "آدرس سرور بیلدر",
        "test" to "تست",
        "connected" to "✅ متصل شد",
        "conn_fail" to "❌ سرور در دسترس نیست",
        "language" to "زبان",
        "auto_mode" to "حالت خودکار (ساخت هر دو پلتفرم)",
        "ai_key" to "کلید هوش مصنوعی (اختیاری، سازگار با OpenAI)",
        "ai_base" to "آدرس پایه AI (اختیاری)",
        "ai_hint" to "بدون کلید، موتور قالب داخلی استفاده می‌شود. با کلید، هوش مصنوعی ظاهر برنامه را برای هر ایده‌ای اختصاصی می‌کند.",
        "about_text" to "فقط یک جمله کوتاه بنویس — برنامه ویندوزی (.exe + فایل نصب Setup) و برنامه اندرویدی (.apk) با نصب مستقیم تحویل بگیر. سورس‌کد و پیش‌نمایش زنده همیشه همراه است.",
        "refresh" to "به‌روزرسانی",
        "empty_apps" to "هنوز چیزی نساختی — از تب سازنده شروع کن 👆",
        "build_this" to "← ساخت این قالب",
        "status_queued" to "در صف",
        "status_building" to "در حال ساخت",
        "status_done" to "آماده",
        "status_partial" to "نیمه‌آماده",
        "status_failed" to "ناموفق",
        "err_create" to "شروع ساخت ناموفق بود: ",
        "api_token" to "توکن امنیتی سرور (اگه سرور توکن می‌خواد)",
        "api_token_hint" to "همان مقدار BUILDER_TOKEN روی سرور. اگه سرور توکن نداره خالی بذار.",
        "err_network" to "به سرور وصل نشد. آدرس، وای‌فای و روشن بودن سرور (start_server) را چک کن.",
        "err_unauth" to "توکن اشتباه است — از تنظیمات اصلاحش کن.",
        "retry" to "↻ تلاش مجدد",
        "srv_help_title" to "📡 اتصال گوشی به سرور چطور؟",
        "srv_help_body" to "۱) روی کامپیوتر وارد پوشه server شو و start_server.bat را اجرا کن (ویندوز) یا ./start_server.sh (لینوکس/مک)\n۲) گوشی را به همان وای‌فای کامپیوتر وصل کن\n۳) آدرسی که توی پنجره مشکی نشون داده (مثل http://192.168.1.5:8000) را بالا در «آدرس سرور» بنویس\n۴) دکمه تست ✓ را بزن — بعد هر چیزی بساز!",
    )
    operator fun get(lang: String, key: String): String =
        (if (lang == "fa") fa else en)[key] ?: en[key] ?: key
}
